version: '3.8'
services:
  restapi:
    build:
      context: .
      target: development
    ports:
      - "80:80"
    environment:
      - DB_URL=jdbc:mysql://mysqlserver/ecommerce_app
      - DB_USERNAME=ecommerce_app
      - DB_PASSWORD=ecommerce_app
      - SERVER_ADDRESS=0.0.0.0
    volumes:
      - ./:/app
    depends_on:
      - mysqlserver

  mysqlserver:
    image: amd64/mysql:8.0
    ports:
      - "127.0.0.1:3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=ecommerce_app
      - MYSQL_PASSWORD=ecommerce_app
      - MYSQL_DATABASE=ecommerce_app
    volumes:
      - mysql_data:/var/lib/mysql
      - mysql_config:/etc/mysql/conf.d
volumes:
  mysql_data:
  mysql_config: